source 'https://rubygems.org'

gem 'nokogiri'
gem 'devise'
gem 'mechanize'
gem 'paperclip'
gem 'trollop'
gem 'awesome_print'
gem 'fakeweb'
gem 'rb-readline'
gem 'rack'
gem 'lite_config'
gem 'redis'
gem 'i18n'
gem 'activesupport'